/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://3xykpo4aa5hjpbeownp3buvumy.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4ftizj7535bhvmdvyzdzdnp3ne",
    "aws_cognito_identity_pool_id": "us-west-1:06a66fc4-e812-445a-a3af-00c65e06604e",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_V7xRtNLyQ",
    "aws_user_pools_web_client_id": "4t3jjcgga2e5rf2c2hjbql1el6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
